import { randomUUID } from 'crypto';
import { minioClient } from '../config/minio';
import { env } from '../config/env';

interface GenerateImageParams {
  prompt: string;
  style?: string;
  aspectRatio?: '1:1' | '9:16' | '4:5';
}

interface GenerateImageResult {
  imageUrl: string;
  minioKey: string;
}

function enrichPrompt(prompt: string, style?: string): string {
  const base = 'Professional social media post, high quality, vibrant colors, modern design';
  return style ? `${base}, ${style} style, ${prompt}` : `${base}, ${prompt}`;
}

// Map aspect ratios to Gemini-supported values
function mapAspectRatio(ratio?: string): string {
  const map: Record<string, string> = {
    '1:1': '1:1',
    '9:16': '9:16',
    '4:5': '3:4', // closest supported by Gemini
  };
  return map[ratio || '1:1'] || '1:1';
}

export async function generateImage(params: GenerateImageParams): Promise<GenerateImageResult> {
  const { getSetting } = await import('../helpers/getSetting');
  const apiKey = await getSetting('NANO_BANANA_API_KEY');
  if (!apiKey) {
    throw new Error('NANO_BANANA_API_KEY not configured - add it in Settings page');
  }

  const enrichedPrompt = enrichPrompt(params.prompt, params.style);
  const model = 'gemini-3.1-flash-image-preview';
  const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

  const body = JSON.stringify({
    contents: [{ parts: [{ text: `Generate an image: ${enrichedPrompt}` }] }],
    generationConfig: {
      responseModalities: ['TEXT', 'IMAGE'],
      imageConfig: {
        aspectRatio: mapAspectRatio(params.aspectRatio),
      },
    },
  });

  let response: globalThis.Response | null = null;
  for (let attempt = 0; attempt < 3; attempt++) {
    response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body,
    });
    if (response.ok || (response.status !== 503 && response.status !== 429)) break;
    console.log(`[Gemini] ${response.status} on attempt ${attempt + 1}, retrying in ${(attempt + 1) * 5}s...`);
    await new Promise(r => setTimeout(r, (attempt + 1) * 5000));
  }

  if (!response!.ok) {
    const errorText = await response!.text();
    throw new Error(`Gemini API error ${response!.status}: ${errorText}`);
  }

  const data = (await response!.json()) as any;

  // Find the image part in the response
  const candidates = data.candidates;
  if (!candidates || candidates.length === 0) {
    throw new Error('No candidates returned from Gemini API');
  }

  const parts = candidates[0].content?.parts || [];
  const imagePart = parts.find((p: any) => p.inlineData?.mimeType?.startsWith('image/'));

  if (!imagePart) {
    throw new Error('No image generated by Gemini API');
  }

  const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');

  if (imageBuffer.length < 1000) {
    throw new Error('Generated image too small, possibly invalid');
  }

  const ext = imagePart.inlineData.mimeType === 'image/jpeg' ? 'jpg' : 'png';
  const contentType = imagePart.inlineData.mimeType;
  const key = `posts/${Date.now()}-${randomUUID()}.${ext}`;

  // Ensure bucket exists before uploading
  const bucketExists = await minioClient.bucketExists(env.MINIO_BUCKET);
  if (!bucketExists) {
    await minioClient.makeBucket(env.MINIO_BUCKET);
    const policy = {
      Version: '2012-10-17',
      Statement: [{ Effect: 'Allow', Principal: { AWS: ['*'] }, Action: ['s3:GetObject'], Resource: [`arn:aws:s3:::${env.MINIO_BUCKET}/*`] }],
    };
    await minioClient.setBucketPolicy(env.MINIO_BUCKET, JSON.stringify(policy));
  }

  await minioClient.putObject(env.MINIO_BUCKET, key, imageBuffer, imageBuffer.length, {
    'Content-Type': contentType,
  });

  const imageUrl = `${env.MINIO_PUBLIC_URL}/${env.MINIO_BUCKET}/${key}`;
  return { imageUrl, minioKey: key };
}
