/**
 * Design Systems Library
 *
 * Reference data extracted from 58 well-known brand design systems.
 * Used by AI agents (via MCP) to suggest brand identities, color palettes,
 * typography choices, and visual principles when users create or refine
 * their own brands in OpenHive.
 *
 * Each entry contains FACTS (color hex codes, font names, weight numbers)
 * combined with original short descriptions of the visual mood and principles.
 */

export type DesignSystemCategory =
  | 'fintech'
  | 'productivity'
  | 'dev-tools'
  | 'ai'
  | 'luxury'
  | 'automotive'
  | 'social'
  | 'media'
  | 'other';

export interface DesignSystem {
  id: string;
  name: string;
  vibe: string;
  category: DesignSystemCategory;
  colors: {
    primary: string;
    secondary: string;
    background: string;
    text: string;
    accent?: string;
  };
  typography: {
    font: string;
    weights: string;
    characteristics: string;
  };
  principles: string[];
  moodKeywords: string[];
}

export const DESIGN_SYSTEMS: DesignSystem[] = [
  {
    id: 'airbnb',
    name: 'Airbnb',
    vibe: 'Warm inviting marketplace for global discovery',
    category: 'social',
    colors: { primary: '#ff385c', secondary: '#460479', background: '#ffffff', text: '#222222', accent: '#428bff' },
    typography: { font: 'Airbnb Cereal VF', weights: '500, 600, 700', characteristics: 'Warm rounded terminals with tight negative letter-spacing create intimate, cozy readability' },
    principles: ['Warm weight range with confident medium-to-bold hierarchy', 'Negative letter-spacing on headings for intimate reading', 'Three-layer card shadows for subtle natural lift', 'Photography-first design with images as hero content'],
    moodKeywords: ['welcoming', 'travel', 'discovery', 'belonging'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    vibe: 'Sophisticated simplicity for enterprise data',
    category: 'productivity',
    colors: { primary: '#1b61c9', secondary: '#254fad', background: '#ffffff', text: '#181d26', accent: '#006400' },
    typography: { font: 'Haas', weights: '400, 500', characteristics: 'Swiss-geometric precision with positive letter-spacing creates well-spaced, professional reading rhythm' },
    principles: ['Haas dual-variant system for display and body clarity', 'Positive letter-spacing throughout for airy readability', 'Blue-tinted multi-layer shadows for depth', 'Enterprise-grade restraint with semantic tokens'],
    moodKeywords: ['clean', 'precise', 'professional', 'organized'],
  },
  {
    id: 'apple',
    name: 'Apple',
    vibe: 'Cinematic product reverence through visual restraint',
    category: 'luxury',
    colors: { primary: '#0071e3', secondary: '#f5f5f7', background: '#000000', text: '#ffffff', accent: '#1d1d1f' },
    typography: { font: 'SF Pro Display / SF Pro Text', weights: '300, 400, 600, 700', characteristics: 'Optically-sized letterforms with universal negative tracking create precise, machined headlines' },
    principles: ['Optical sizing automatically adjusts letterforms by context', 'Cinematic black-and-white section alternation for rhythm', 'Single accent color reserved exclusively for interactive elements', 'Pill-shaped CTAs with extreme radius create signature soft rectangles'],
    moodKeywords: ['premium', 'precise', 'iconic', 'minimal'],
  },
  {
    id: 'bmw',
    name: 'BMW',
    vibe: 'Engineering precision rendered in austere geometry',
    category: 'automotive',
    colors: { primary: '#1c69d4', secondary: '#0653b6', background: '#ffffff', text: '#262626', accent: '#757575' },
    typography: { font: 'BMWTypeNextLatin', weights: '300, 400, 700, 900', characteristics: 'Light display weight whispers authority while weight 900 nav creates extreme contrast' },
    principles: ['Light-weight display headlines create whispered elegance', 'Weight 900 navigation provides stark authority contrast', 'Zero border-radius throughout - angular geometric precision', 'Tight line-heights everywhere reflect compressed efficiency'],
    moodKeywords: ['german', 'engineered', 'luxury', 'sharp'],
  },
  {
    id: 'cal',
    name: 'Cal.com',
    vibe: 'Grayscale boldness through monochromatic confidence',
    category: 'productivity',
    colors: { primary: '#242424', secondary: '#111111', background: '#ffffff', text: '#242424', accent: '#0099ff' },
    typography: { font: 'Cal Sans / Inter', weights: '300, 400, 600', characteristics: 'Cal Sans at tight line-heights creates dense architectural headlines, Inter provides readable body clarity' },
    principles: ['Cal Sans display-only for dense headlines at weight 600', 'Aggressive negative letter-spacing at large sizes', 'Multi-layered ring shadows create shadow-as-border depth', 'Purely grayscale palette emphasizes boldness through contrast'],
    moodKeywords: ['scheduling', 'minimal', 'monochrome', 'confident'],
  },
  {
    id: 'claude',
    name: 'Claude',
    vibe: 'Literary warmth meeting intellectual conversation',
    category: 'ai',
    colors: { primary: '#c96442', secondary: '#5e5d59', background: '#f5f4ed', text: '#141413', accent: '#3898ec' },
    typography: { font: 'Anthropic Serif / Anthropic Sans', weights: '400, 500', characteristics: 'Medium-weight serif conveys gravitas while sans handles utility with quiet efficiency' },
    principles: ['Serif for authority, sans for functional clarity', 'Exclusively warm-toned neutrals with yellow-brown undertone', 'Ring-based shadow system creates border-like halos', 'Organic editorial illustrations replace typical tech iconography'],
    moodKeywords: ['thoughtful', 'warm', 'literary', 'human'],
  },
  {
    id: 'clay',
    name: 'Clay',
    vibe: 'Playful data enrichment with craft-like warmth',
    category: 'dev-tools',
    colors: { primary: '#000000', secondary: '#9f9b93', background: '#faf9f7', text: '#000000', accent: '#078a52' },
    typography: { font: 'Roobert', weights: '400, 500, 600', characteristics: 'Roobert with five stylistic sets creates geometric personality through contextual swash alternates' },
    principles: ['All five OpenType stylistic sets define brand personality', 'Playful hover animations rotate and shadow hard-offset style', 'Warm oat-toned borders and dashed styles add craft quality', 'Named swatch palette treats colors like juice bar flavors'],
    moodKeywords: ['playful', 'colorful', 'crafted', 'joy'],
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    vibe: 'Speed screams through electrifying contrast',
    category: 'dev-tools',
    colors: { primary: '#faff69', secondary: '#166534', background: '#000000', text: '#ffffff', accent: '#f4f692' },
    typography: { font: 'Inter', weights: '400, 500, 600, 700, 900', characteristics: 'Inter Black at display sizes creates text with physical mass, conveying raw database power' },
    principles: ['Weight 900 display headlines establish raw power presence', 'Neon yellow-green on pure black creates maximum contrast', 'Inset shadows create pressed-into-surface depth effect', 'Performance stats displayed as oversized numbers'],
    moodKeywords: ['fast', 'powerful', 'electric', 'intense'],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    vibe: 'Enterprise command deck with polished precision',
    category: 'ai',
    colors: { primary: '#1863dc', secondary: '#9b60aa', background: '#ffffff', text: '#000000', accent: '#212121' },
    typography: { font: 'CohereText / Unica77', weights: '400, 500', characteristics: 'Serif display gives research authority while Swiss sans provides geometric precision' },
    principles: ['Serif headlines carry technology-manifesto gravitas', 'Large border-radius creates signature organic cloud-like roundness', 'Enterprise photography provides dramatic visual breaks', 'Ghost buttons that shift blue on hover signal interactivity'],
    moodKeywords: ['enterprise', 'confident', 'professional', 'trusted'],
  },
  {
    id: 'coinbase',
    name: 'Coinbase',
    vibe: 'Trustworthy fintech through blue-white binary',
    category: 'fintech',
    colors: { primary: '#0052ff', secondary: '#578bfa', background: '#ffffff', text: '#0a0b0d', accent: '#eef0f3' },
    typography: { font: 'CoinbaseDisplay / CoinbaseSans', weights: '400, 500, 600, 700', characteristics: 'Proprietary font family creates distinctive brand voice through four specialized variants' },
    principles: ['Pill-shaped buttons with generous radius create approachable CTA shapes', 'Ultra-tight display line-heights compress impact', 'Clean dark-white section alternation establishes hierarchy', 'Lowercase button labels create unusual typographic personality'],
    moodKeywords: ['financial', 'trustworthy', 'modern', 'clean'],
  },
  {
    id: 'composio',
    name: 'Composio',
    vibe: 'Developer terminal aesthetic with bioluminescent glow',
    category: 'dev-tools',
    colors: { primary: '#0007cd', secondary: '#00ffff', background: '#0f0f0f', text: '#ffffff', accent: '#0089ff' },
    typography: { font: 'abcDiatype / JetBrains Mono', weights: '400, 500', characteristics: 'Geometric sans carries marketing voice while monospace conveys developer credibility' },
    principles: ['Ultra-tight heading line-heights compress text into density', 'Border-mist opacity layers create subtle depth without shadows', 'Hard-offset brutalist shadows add raw, retro-computing edge', 'Cyan glow halos create bioluminescent emission effect'],
    moodKeywords: ['developer', 'technical', 'dark', 'nocturnal'],
  },
  {
    id: 'cursor',
    name: 'Cursor',
    vibe: 'Warm minimalism meets code-editor craftsmanship',
    category: 'dev-tools',
    colors: { primary: '#f54e00', secondary: '#26251e', background: '#f2f1ed', text: '#26251e', accent: '#cf2d56' },
    typography: { font: 'CursorGothic / jjannon', weights: '400, 500', characteristics: 'Gothic compression at display creates engineered precision while serif body adds literary warmth' },
    principles: ['Aggressive negative letter-spacing compresses gothic headlines', 'Warm off-white background permeates entire system', 'Perceptual color space borders maintain visual consistency', 'Contextual swash alternates on serif body text add calligraphy'],
    moodKeywords: ['warm', 'crafted', 'engineered', 'literary'],
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    vibe: 'Ethereal lightness whispers audio-first presence',
    category: 'ai',
    colors: { primary: '#000000', secondary: '#4e4e4e', background: '#ffffff', text: '#000000', accent: '#f5f2ef' },
    typography: { font: 'Waldenburg / Inter', weights: '300, 400, 500, 700', characteristics: 'Light-weight Waldenburg creates whisper-thin ethereal presence while Inter provides solid readability' },
    principles: ['Weight 300 display creates whisper-thin audio-wave appearance', 'Multi-layered low-opacity shadows barely exist', 'Warm stone pill buttons carry signature tactile quality', 'Inset half-pixel borders define edges through feeling not sight'],
    moodKeywords: ['ethereal', 'audio', 'premium', 'minimal'],
  },
  {
    id: 'expo',
    name: 'Expo',
    vibe: 'Luminous developer gallery with generous breathing',
    category: 'dev-tools',
    colors: { primary: '#000000', secondary: '#60646c', background: '#f0f0f3', text: '#1c2024', accent: '#0d74ce' },
    typography: { font: 'Inter', weights: '400, 600, 700, 900', characteristics: 'Single typeface achieves full expression through extreme weight range and aggressive negative tracking' },
    principles: ['Extreme negative letter-spacing at display creates ultra-dense headlines', 'One typeface, full weight range creates unified expressive voice', 'Pill-shaped geometry everywhere signals friendliness', 'Gallery-like pacing with enormous section spacing'],
    moodKeywords: ['luminous', 'gallery', 'friendly', 'developer'],
  },
  {
    id: 'ferrari',
    name: 'Ferrari',
    vibe: 'Editorial luxury through cinematic chiaroscuro',
    category: 'automotive',
    colors: { primary: '#da291c', secondary: '#303030', background: '#000000', text: '#ffffff', accent: '#181818' },
    typography: { font: 'FerrariSans / Body-Font', weights: '400, 500, 600, 700', characteristics: 'FerrariSans carries editorial narrative while uppercase Body-Font provides structural annotation' },
    principles: ['Signature red reserved with surgical sparseness for maximum impact', 'Chiaroscuro alternation between black cinematic and white editorial', 'Iconic emblem floats isolated on void-black field', 'Zero border-radius reflects razor precision engineering'],
    moodKeywords: ['editorial', 'luxurious', 'cinematic', 'precise'],
  },
  {
    id: 'figma',
    name: 'Figma',
    vibe: 'Minimalist precision meets vibrant possibility',
    category: 'dev-tools',
    colors: { primary: '#000000', secondary: '#ffffff', background: '#ffffff', text: '#000000', accent: '#0099ff' },
    typography: { font: 'figmaSans', weights: '320, 330, 340, 450, 480, 540, 700', characteristics: 'Custom variable font with granular weight control creates hierarchy through micro-differences rather than bold jumps' },
    principles: ['Variable font precision enables subtle visual weight hierarchy', 'Monochrome interface with colorful product content separation', 'Pill-shaped buttons and circular geometry throughout', 'Negative letter-spacing on all text for tight compression'],
    moodKeywords: ['precise', 'tool-obsessed', 'editorial', 'minimalist'],
  },
  {
    id: 'framer',
    name: 'Framer',
    vibe: 'Dark nightclub for designers with electric precision',
    category: 'dev-tools',
    colors: { primary: '#000000', secondary: '#ffffff', background: '#000000', text: '#ffffff', accent: '#0099ff' },
    typography: { font: 'GT Walsheim', weights: '500', characteristics: 'Geometric sans-serif with extreme negative letter-spacing creates compressed, spring-loaded headlines that feel kinetic' },
    principles: ['Extreme compression at display sizes defines brand voice', 'OpenType features maximize micro-typography refinement', 'Product screenshots serve as hero content and proof', 'Blue-tinted ring shadows for subtle depth signaling'],
    moodKeywords: ['dark', 'electric', 'compressed', 'kinetic'],
  },
  {
    id: 'hashicorp',
    name: 'HashiCorp',
    vibe: 'Enterprise infrastructure with approachable precision',
    category: 'dev-tools',
    colors: { primary: '#000000', secondary: '#ffffff', background: '#15181e', text: '#ffffff', accent: '#7b42bc' },
    typography: { font: 'HashiCorp Sans', weights: '600, 700', characteristics: 'Dense, load-bearing headings with tight line-heights convey infrastructure confidence and technical authority' },
    principles: ['Multi-product color system via CSS variables for brand expression', 'Micro-shadows at whisper level signal interactivity without noise', 'Tight headings paired with relaxed body creates weight hierarchy', 'Uppercase labels serve as systematic wayfinding markers'],
    moodKeywords: ['enterprise', 'authoritative', 'systematic', 'stable'],
  },
  {
    id: 'ibm',
    name: 'IBM',
    vibe: 'Corporate precision through systematic tokenization',
    category: 'dev-tools',
    colors: { primary: '#ffffff', secondary: '#161616', background: '#ffffff', text: '#161616', accent: '#0f62fe' },
    typography: { font: 'IBM Plex Sans', weights: '300, 400, 600', characteristics: 'Light weight at display sizes creates corporate gravitas through typographic restraint rather than boldness' },
    principles: ['Token-driven architecture enables enterprise scalability', 'Micro-tracking creates legibility at compact sizes', 'Background layering replaces shadows for flat design depth', 'Rectangular corners and sharp geometry reflect corporate precision'],
    moodKeywords: ['corporate', 'engineered', 'systematic', 'accessible'],
  },
  {
    id: 'intercom',
    name: 'Intercom',
    vibe: 'Warm customer service made approachable',
    category: 'ai',
    colors: { primary: '#111111', secondary: '#ffffff', background: '#faf9f6', text: '#111111', accent: '#ff5600' },
    typography: { font: 'Saans', weights: '400', characteristics: 'Aggressive negative letter-spacing and tight line-height creates compressed, billboard-like headlines with industrial precision' },
    principles: ['Extreme negative tracking on headings compresses text into impact', 'Sharp geometry contradicts warm color palette for tension', 'Warm neutral borders create gentle containment without weight', 'Scale-based button hover interactions feel physical and responsive'],
    moodKeywords: ['warm', 'precise', 'industrial', 'confident'],
  },
  {
    id: 'kraken',
    name: 'Kraken',
    vibe: 'Trustworthy crypto exchange with purple authority',
    category: 'fintech',
    colors: { primary: '#7132f5', secondary: '#ffffff', background: '#ffffff', text: '#101114', accent: '#149e61' },
    typography: { font: 'Kraken-Brand', weights: '700', characteristics: 'Bold display headings paired with light UI font creates functional duality balancing brand presence with usability' },
    principles: ['Purple brand identity establishes crypto credibility', 'Rounded button geometry softens corporate structure', 'Dual font system separates branding from interface function', 'Subtle shadow whispers signal interactivity restraint'],
    moodKeywords: ['trustworthy', 'professional', 'purple-dominant', 'crypto'],
  },
  {
    id: 'lamborghini',
    name: 'Lamborghini',
    vibe: 'Dark luxury through dramatic contrast and gold',
    category: 'automotive',
    colors: { primary: '#000000', secondary: '#ffffff', background: '#000000', text: '#ffffff', accent: '#FFC000' },
    typography: { font: 'LamboType', weights: '400', characteristics: 'Uppercase at all scales with tight line-heights creates architectural, stamped-from-steel text blocks at any size' },
    principles: ['ALL-CAPS is the default voice commanding aggressive presence', 'Zero border-radius rectangles echo uncompromising vehicle lines', 'Darkness as whitespace lets each element float as exhibit', 'Hexagonal geometry echoes aerodynamic DNA throughout UI'],
    moodKeywords: ['dark', 'aggressive', 'luxury', 'theatrical'],
  },
  {
    id: 'linear',
    name: 'Linear',
    vibe: 'Dark precision engineered for efficiency',
    category: 'dev-tools',
    colors: { primary: '#08090a', secondary: '#f7f8f8', background: '#08090a', text: '#f7f8f8', accent: '#5e6ad2' },
    typography: { font: 'Inter Variable', weights: '300, 400, 510, 590', characteristics: 'Signature weight 510 sits between regular and medium, enabling subtle emphasis without shouting' },
    principles: ["Weight 510 serves as Linear's signature emphasis weight", 'Darkness as native medium manages density through luminance steps', 'OpenType features transform Inter into geometric variant', 'Semi-transparent white borders create structure without visual noise'],
    moodKeywords: ['engineered', 'dark', 'precise', 'efficient'],
  },
  {
    id: 'lovable',
    name: 'Lovable',
    vibe: 'Warm approachable tool design with humanist touch',
    category: 'dev-tools',
    colors: { primary: '#1c1c1c', secondary: '#fcfbf8', background: '#f7f4ed', text: '#1c1c1c', accent: '#3b82f6' },
    typography: { font: 'Camera Plain Variable', weights: '400, 480, 600', characteristics: 'Humanist warmth with organic curves and slightly rounded terminals creates approachable reading rhythm' },
    principles: ['Opacity-driven grays all derive from single hue for tonal unity', 'Variable font enables nuanced intermediary weights like 480', 'Inset shadows on buttons create tactile pressed-into-surface feeling', 'Full-pill radius reserved only for action toggles and icon buttons'],
    moodKeywords: ['warm', 'humanist', 'approachable', 'tactile'],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    vibe: 'Playful AI gallery with modern rounded elegance',
    category: 'ai',
    colors: { primary: '#181e25', secondary: '#ffffff', background: '#ffffff', text: '#222222', accent: '#1456f0' },
    typography: { font: 'DM Sans', weights: '400, 500, 600, 700', characteristics: 'Multi-font system where DM Sans drives UI, Outfit handles display, creating purposeful typographic differentiation' },
    principles: ['Multi-font ecosystem each serves distinct communicative role', 'Vibrant gradient product cards pop from white canvas', 'Pill navigation tabs establish modern interaction patterns', 'Purple-tinted shadows connect depth system to brand identity'],
    moodKeywords: ['playful', 'modern', 'colorful', 'gallery-like'],
  },
  {
    id: 'mintlify',
    name: 'Mintlify',
    vibe: 'Documentation clarity through minimalist elegance',
    category: 'dev-tools',
    colors: { primary: '#0d0d0d', secondary: '#ffffff', background: '#ffffff', text: '#0d0d0d', accent: '#18E299' },
    typography: { font: 'Inter', weights: '400, 500, 600', characteristics: 'Tight negative tracking at display sizes creates focused, space-efficient headlines matching documentation quality' },
    principles: ['Five percent opacity borders replace shadows for subtle separation', 'Full-pill buttons and inputs establish signature shape language', 'Atmospheric gradient hero creates ethereal intelligence feeling', 'Ultra-round corners convey approachable documentation experience'],
    moodKeywords: ['clarity', 'minimal', 'intelligent', 'airy'],
  },
  {
    id: 'miro',
    name: 'Miro',
    vibe: 'Collaborative white canvas with pastel accents',
    category: 'productivity',
    colors: { primary: '#1c1c1e', secondary: '#ffffff', background: '#ffffff', text: '#1c1c1e', accent: '#5b76fe' },
    typography: { font: 'Roobert PRO Medium', weights: '400, 600, 700', characteristics: 'OpenType character variants create cleaner geometric appearance with negative tracking at display sizes' },
    principles: ['Pastel light and dark pairs represent different collaboration contexts', 'Ring shadow borders create containment without visual weight', 'Generous rounded corners establish approachable tool aesthetic', 'Blue interactive color signals primary actions and engagement'],
    moodKeywords: ['collaborative', 'playful', 'pastel', 'approachable'],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    vibe: 'Warm luxury European AI with golden intensity',
    category: 'ai',
    colors: { primary: '#1f1f1f', secondary: '#ffffff', background: '#fffaeb', text: '#1f1f1f', accent: '#fa520f' },
    typography: { font: 'Arial', weights: '400', characteristics: 'Single weight at massive scales with extreme negative tracking creates poster-like declarations' },
    principles: ['Single weight throughout with hierarchy from size and color only', 'Warm golden shadow cascade creates golden-hour lighting effect', 'Sharp architectural corners contrast with warm color palette tension', 'Uppercase labels establish European formality and signage quality'],
    moodKeywords: ['warm', 'golden', 'bold', 'luxury'],
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    vibe: 'Forest-dark database with electric neon growth',
    category: 'dev-tools',
    colors: { primary: '#001e2b', secondary: '#ffffff', background: '#001e2b', text: '#ffffff', accent: '#00ed64' },
    typography: { font: 'MongoDB Value Serif', weights: '400, 500, 700', characteristics: 'Serif headlines create editorial authority unusual for database companies, while geometric body font drives pragmatic function' },
    principles: ['Serif authority distinguishes from typical startup tech brands', 'Light body text creates airy reading against dark backgrounds', 'Teal-tinted shadows carry forest color through depth system', 'Wide-tracked monospace labels establish technical database voice'],
    moodKeywords: ['authoritative', 'dark', 'forest-like', 'editorial'],
  },
  {
    id: 'notion',
    name: 'Notion',
    vibe: 'Blank canvas that gets out of the way',
    category: 'productivity',
    colors: { primary: '#ffffff', secondary: '#f6f5f4', background: '#ffffff', text: '#000000', accent: '#0075de' },
    typography: { font: 'NotionInter', weights: '400, 500, 600, 700', characteristics: 'Warm grays with yellow undertones soften interface while negative tracking at scale creates compressed headlines' },
    principles: ['Warm neutral palette creates analog tactile feeling', 'Whisper-thin 1px borders replace shadows for barely-there structure', 'Multi-layer shadow stacks create felt rather than seen depth', 'Warm white section alternation establishes gentle visual rhythm'],
    moodKeywords: ['minimal', 'warm', 'tactile', 'approachable'],
  },
  {
    id: 'nvidia',
    name: 'NVIDIA',
    vibe: 'Precision engineering rendered in pixels',
    category: 'dev-tools',
    colors: { primary: '#76b900', secondary: '#1a1a1a', background: '#000000', text: '#ffffff', accent: '#3860be' },
    typography: { font: 'NVIDIA-EMEA', weights: '400, 700', characteristics: 'Industrial, European, and confident with bold weights dominating headings and UI elements throughout' },
    principles: ['Green accent reserved for borders and interactive signals only', 'Tight 1.25 line-height on headings, relaxed body for contrast', 'Sharp small border radius throughout for engineered aesthetic', 'Uppercase navigation creating hardware specification labels'],
    moodKeywords: ['industrial', 'technical', 'authoritative', 'precision'],
  },
  {
    id: 'ollama',
    name: 'Ollama',
    vibe: 'Radical minimalism with softened edges',
    category: 'ai',
    colors: { primary: '#000000', secondary: '#e5e5e5', background: '#ffffff', text: '#262626', accent: '#3b82f6' },
    typography: { font: 'SF Pro Rounded', weights: '400, 500', characteristics: 'Rounded system font bringing distinctive softness and approachability to developer tools' },
    principles: ['Pure grayscale with zero chromatic color except focus ring', 'Binary border-radius system: pill-shaped interactive elements, large containers', 'No shadows whatsoever, depth from background color shifts only', 'Minimal content density with generous negative space'],
    moodKeywords: ['minimal', 'warm', 'approachable', 'softness'],
  },
  {
    id: 'opencode',
    name: 'OpenCode',
    vibe: 'Terminal-native monospace aesthetic',
    category: 'dev-tools',
    colors: { primary: '#201d1d', secondary: '#fdfcfc', background: '#201d1d', text: '#fdfcfc', accent: '#007aff' },
    typography: { font: 'Berkeley Mono', weights: '400, 500, 700', characteristics: 'Single monospace font throughout establishing unified code-first identity with no serif or sans-serif alternatives' },
    principles: ['Warm near-black with reddish undertone, never pure black', 'Minimal small border radius throughout maintaining utilitarian feel', 'Apple HIG semantic colors for trusted signal system', 'Generous line-heights enabling legibility within monospace grid'],
    moodKeywords: ['warm', 'monospace', 'coded', 'utilitarian'],
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    vibe: 'Cozy craft-like editorial experience',
    category: 'social',
    colors: { primary: '#e60023', secondary: '#e5e5e0', background: '#ffffff', text: '#211922', accent: '#435ee5' },
    typography: { font: 'Pin Sans', weights: '400, 700', characteristics: 'Compact type scale with negative tracking on headings creating intimate, cozy section titles' },
    principles: ['Warm olive and sand neutrals replacing typical cool grays throughout', 'Generous border-radius creates handcrafted feeling', 'Plum-black text warmer than pure black for approachable aesthetic', 'Photography as primary visual element with minimal UI decoration'],
    moodKeywords: ['warm', 'handcrafted', 'inspiration', 'photography'],
  },
  {
    id: 'posthog',
    name: 'PostHog',
    vibe: 'Scrappy startup wiki meets design sophistication',
    category: 'dev-tools',
    colors: { primary: '#4d4f46', secondary: '#eeefe9', background: '#fdfdf8', text: '#4d4f46', accent: '#F54E00' },
    typography: { font: 'IBM Plex Sans Variable', weights: '400, 600, 700, 800', characteristics: 'Bold heading dominance with generous body line-heights creating comfortable reading on content-heavy site' },
    principles: ['Hidden brand orange appearing only on hover interactions', 'Olive and sage palette replacing conventional blues creating earthy approach', 'Hand-drawn illustrations as signature visual element', 'Content-dense editorial layout with magazine-like pacing'],
    moodKeywords: ['scrappy', 'playful', 'earthy', 'irreverent'],
  },
  {
    id: 'raycast',
    name: 'Raycast',
    vibe: 'Precision instrument carved from obsidian',
    category: 'productivity',
    colors: { primary: '#07080a', secondary: '#101111', background: '#07080a', text: '#f9f9f9', accent: '#FF6363' },
    typography: { font: 'Inter', weights: '400, 500, 600', characteristics: 'Positive letter-spacing creates airy dark-mode reading experience contrasting dense display text' },
    principles: ['Blue-tinted near-black background never pure black for subtle cool tone', 'Multi-layer inset shadows simulating physical depth and light sources', 'Red used sparingly as punctuation in hero moments and danger states', 'OpenType features enabled globally for precise typographic control'],
    moodKeywords: ['precise', 'dark', 'swiss', 'macos-native'],
  },
  {
    id: 'renault',
    name: 'Renault',
    vibe: 'Energized automotive showroom with geometric precision',
    category: 'automotive',
    colors: { primary: '#EFDF00', secondary: '#000000', background: '#ffffff', text: '#000000', accent: '#1883FD' },
    typography: { font: 'NouvelR', weights: '400, 600, 700', characteristics: 'Ultra-tight line-height on display text creates dense, punchy typographic texture feeling urgent' },
    principles: ['Zero border-radius on buttons expressing precision engineering identity', 'Vivid aurora gradients on hero sections providing atmospheric richness', 'Card-based editorial grid with full-bleed photography and dark overlays', 'Yellow reserved exclusively for super-primary CTAs maintaining hierarchy'],
    moodKeywords: ['energetic', 'geometric', 'cinematic', 'automotive'],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    vibe: 'Creative explosion meets developer playfulness',
    category: 'ai',
    colors: { primary: '#202020', secondary: '#fcfcfc', background: '#ffffff', text: '#202020', accent: '#ea2804' },
    typography: { font: 'rb-freigeist-neue', weights: '400, 600, 700', characteristics: 'Massive display weight creating thundering headlines that demand attention and express creative joy' },
    principles: ['Exclusively pill-shaped radius throughout entire system without exception', 'Explosive orange-red-magenta gradient hero dominating visual hierarchy', 'Community-powered energy through model galleries and creative imagery', 'Dotted underline links creating casual developer-friendly aesthetic'],
    moodKeywords: ['explosive', 'creative', 'playful', 'community'],
  },
  {
    id: 'resend',
    name: 'Resend',
    vibe: 'Cinematic void stage for email infrastructure',
    category: 'dev-tools',
    colors: { primary: '#000000', secondary: '#f0f0f0', background: '#000000', text: '#f0f0f0', accent: '#ff801f' },
    typography: { font: 'Domaine Display', weights: '400, 500, 600', characteristics: 'Three-font hierarchy with aggressive negative tracking on display creating compressed, magazine-masthead urgency' },
    principles: ['Icy blue-tinted frost borders instead of neutral gray for crystalline quality', 'Three-tier editorial hierarchy with distinct typographic voices per layer', 'Multi-color accent system with low-opacity backgrounds for context highlighting', 'Pill-shaped primary CTAs contrasting subtle rectangular secondary actions'],
    moodKeywords: ['premium', 'cinematic', 'technical', 'precise'],
  },
  {
    id: 'revolut',
    name: 'Revolut',
    vibe: 'Fintech confidence at stadium scale',
    category: 'fintech',
    colors: { primary: '#191c1f', secondary: '#f4f4f4', background: '#ffffff', text: '#191c1f', accent: '#494fdf' },
    typography: { font: 'Aeonik Pro', weights: '400, 500, 600', characteristics: 'Billboard-scale headlines with aggressive negative tracking projecting authority through size and spacing alone' },
    principles: ['Universal pill buttons with generous padding creating confident touch targets', 'Weight 500 dominance on display avoiding bold for subtle authority signal', 'Zero shadows throughout relying entirely on color contrast for depth', 'Positive letter-spacing on body creating airy contrast with compressed display'],
    moodKeywords: ['confident', 'financial', 'modern', 'accessible'],
  },
  {
    id: 'runway',
    name: 'Runway',
    vibe: 'Cinematic reel brought to digital life',
    category: 'ai',
    colors: { primary: '#000000', secondary: '#ffffff', background: '#000000', text: '#404040', accent: '#767d88' },
    typography: { font: 'abcNormal', weights: '400, 600', characteristics: 'Single geometric sans throughout with tight line-heights and negative tracking creating film-title density' },
    principles: ['Full-bleed cinematic photography as primary UI element, interface nearly invisible', 'Cool gray neutral palette without warm tinting maintaining precision', 'Tight editorial line-heights across all sizes reinforcing dense aesthetic', 'Precision micro-weight tool for labels signaling sophistication'],
    moodKeywords: ['cinematic', 'editorial', 'visual', 'invisible-interface'],
  },
  {
    id: 'sanity',
    name: 'Sanity',
    vibe: 'Nocturnal command center for structured content',
    category: 'dev-tools',
    colors: { primary: '#0b0b0b', secondary: '#212121', background: '#0b0b0b', text: '#ffffff', accent: '#f36458' },
    typography: { font: 'waldenburgNormal', weights: '400, 425, 500, 600', characteristics: 'Extreme negative tracking at display sizes creating precision-engineered typographic voice feeling machined' },
    principles: ['Pure achromatic gray scale maintaining neutral discipline without warm or cool bias', 'Vivid accent punctuation in neon green and electric blue against dark field', 'Pill-shaped primary buttons contrasting subtle rounded rectangle secondary actions', 'OpenType feature control fine-tuning character alternates for different contexts'],
    moodKeywords: ['engineered', 'controlled', 'technical', 'signal-lights'],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    vibe: 'Dark IDE aesthetic with irreverent personality',
    category: 'dev-tools',
    colors: { primary: '#1f1633', secondary: '#79628c', background: '#1f1633', text: '#ffffff', accent: '#c2ef4e' },
    typography: { font: 'Dammit Sans', weights: '400, 500, 600, 700', characteristics: 'Dual personality with bold display bringing brand attitude while Rubik provides clean functional professionalism' },
    principles: ['Warm purple tones replacing typical cool grays creating approachable darkness', 'Inset shadows on buttons creating tactile pressed-into-surface quality', 'Uppercase throughout with letter-spacing creating systematic technical label pattern', 'Lime green accent used sparingly for maximum impact and visibility'],
    moodKeywords: ['irreverent', 'warm-purple', 'technical', 'tactile'],
  },
  {
    id: 'spacex',
    name: 'SpaceX',
    vibe: 'Cinematic aerospace exhibition with precision labeling',
    category: 'other',
    colors: { primary: '#000000', secondary: '#f0f0fa', background: '#000000', text: '#f0f0fa' },
    typography: { font: 'D-DIN', weights: '400, 700', characteristics: 'Universal uppercase with positive letter-spacing creating military aerospace stencil aesthetic throughout' },
    principles: ['Full-viewport photography as primary design element with text overlay only', 'Zero shadows, cards, or containers maintaining invisible interface design', 'Spectral white with blue-violet tint replacing pure white for starlight effect', 'Ghost button with barely-visible spectral border as sole interactive element'],
    moodKeywords: ['cinematic', 'aerospace', 'minimal', 'photography'],
  },
  {
    id: 'spotify',
    name: 'Spotify',
    vibe: 'Dark immersion where music becomes the color',
    category: 'media',
    colors: { primary: '#1ed760', secondary: '#ffffff', background: '#121212', text: '#ffffff', accent: '#b3b3b3' },
    typography: { font: 'SpotifyMixUI / CircularSp', weights: '400, 600, 700', characteristics: 'Bold-regular binary creates strong hierarchy through weight contrast rather than size variation' },
    principles: ['Album art provides all color, UI recedes into shadow', 'Pill buttons with heavy shadows create tactile elevation', 'Uppercase button text with wide letter-spacing signals actions clearly', 'Content density over breathing room reflects app-focused design'],
    moodKeywords: ['dark', 'musical', 'immersive', 'tactile'],
  },
  {
    id: 'stripe',
    name: 'Stripe',
    vibe: 'Confident luxury through engineering precision',
    category: 'fintech',
    colors: { primary: '#533afd', secondary: '#061b31', background: '#ffffff', text: '#061b31', accent: '#ea2261' },
    typography: { font: 'sohne-var', weights: '300, 400', characteristics: 'Light weight at display sizes creates ethereal authority; tracking tightens proportionally to size for compression' },
    principles: ['Light headlines whisper authority instead of shouting', 'Blue-tinted shadows tie elevation to brand palette chromatic depth', 'Tabular numerals for financial data display with precision', 'Conservative border radius maintains professional restraint'],
    moodKeywords: ['precise', 'premium', 'financial', 'ethereal'],
  },
  {
    id: 'supabase',
    name: 'Supabase',
    vibe: 'Developer platform with terminal-inspired sophistication',
    category: 'dev-tools',
    colors: { primary: '#3ecf8e', secondary: '#171717', background: '#0f0f0f', text: '#fafafa', accent: '#00c573' },
    typography: { font: 'Circular', weights: '400, 500', characteristics: 'Geometric rounded terminals create warmth in technical UI; zero-waste hero compression at minimal line-height' },
    principles: ['Dark mode native with border-defined depth hierarchy', 'Green accent sparingly used as identity marker', 'HSL tokens with alpha channels enable translucent layering', 'Monospace labels signal developer-context moments'],
    moodKeywords: ['technical', 'open-source', 'dark', 'efficient'],
  },
  {
    id: 'superhuman',
    name: 'Superhuman',
    vibe: 'Productivity tool marketed as luxury brand',
    category: 'productivity',
    colors: { primary: '#1b1938', secondary: '#cbb7fb', background: '#ffffff', text: '#292827', accent: '#714cb6' },
    typography: { font: 'Super Sans VF', weights: '460, 540, 600, 700', characteristics: 'Non-standard weights between conventions create subtle confidence; extreme display compression contrasts generous body line-height' },
    principles: ['Dramatic hero gradient yields to white canvas instantly', 'Warm cream buttons avoid aggressive CTA colors', 'Only two border radii enforce radical simplicity', 'Product screenshots dominate visual narrative'],
    moodKeywords: ['refined', 'confident', 'minimal', 'luxury'],
  },
  {
    id: 'tesla',
    name: 'Tesla',
    vibe: 'Gallery of technology through photography restraint',
    category: 'automotive',
    colors: { primary: '#3E6AE1', secondary: '#ffffff', background: '#ffffff', text: '#171A20', accent: '#393C41' },
    typography: { font: 'Universal Sans', weights: '400, 500', characteristics: 'No manipulation of letterforms; geometric precision allows typeface to speak for itself without decorative tracking' },
    principles: ['Photography carries all emotional weight; UI dissolves', 'Single blue accent preserves monochromatic discipline', 'Viewport-height sections create gallery browsing experience', 'Pill buttons paired with secondary alternates for dual actions'],
    moodKeywords: ['cinematic', 'minimalist', 'automotive', 'precise'],
  },
  {
    id: 'together',
    name: 'Together AI',
    vibe: 'Enterprise AI that feels light and optimistic',
    category: 'ai',
    colors: { primary: '#ef2cc1', secondary: '#010120', background: '#ffffff', text: '#000000', accent: '#bdbbff' },
    typography: { font: 'The Future', weights: '400, 500', characteristics: 'Negative letter-spacing at every size creates text that feels minified; uppercase monospace labels structure pages technologically' },
    principles: ['Pastel gradients soften technical infrastructure messaging', 'Dark blue sections separate business (light) from research (dark)', 'Enterprise stats displayed prominently with bold numbers', 'Sharp small radius geometry contrasts soft gradient illustrations'],
    moodKeywords: ['optimistic', 'technical', 'enterprise', 'playful'],
  },
  {
    id: 'uber',
    name: 'Uber',
    vibe: 'Confident minimalism through black and white discipline',
    category: 'other',
    colors: { primary: '#000000', secondary: '#ffffff', background: '#ffffff', text: '#000000', accent: '#393C41' },
    typography: { font: 'UberMove / UberMoveText', weights: '400, 500, 700', characteristics: 'Bold headlines demand attention; geometric square proportions feel engineered; no decorative type treatments' },
    principles: ['Pure black-white palette eliminates color distraction', 'Pill buttons become distinctive identity marker', 'Warm human illustrations soften monochromatic system', 'Transit-system density packs information efficiently'],
    moodKeywords: ['bold', 'efficient', 'monochrome', 'urban'],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    vibe: 'Developer infrastructure stripped to essential structure',
    category: 'dev-tools',
    colors: { primary: '#171717', secondary: '#ffffff', background: '#ffffff', text: '#171717', accent: '#ff5b4f' },
    typography: { font: 'Geist', weights: '400, 500, 600', characteristics: 'Aggressive negative letter-spacing compresses text like minified code; ligatures enable structural typographic efficiency' },
    principles: ['Shadow-as-border technique replaces traditional borders', 'Extreme whitespace signals confident restraint', 'Three weights create hierarchy through size and spacing', 'Workflow colors mark pipeline stages contextually'],
    moodKeywords: ['engineered', 'minimal', 'precise', 'developer'],
  },
  {
    id: 'voltagent',
    name: 'VoltAgent',
    vibe: 'AI engineering platform electrified by emerald accent',
    category: 'ai',
    colors: { primary: '#00d992', secondary: '#101010', background: '#050507', text: '#f2f2f2', accent: '#2fd6a1' },
    typography: { font: 'system-ui / Inter', weights: '300, 400, 500, 600, 700', characteristics: 'System fonts for authority and speed; Inter for precision; tight heading compression creates dense technical specifications' },
    principles: ['Emerald glow animates logo with electrical energy', 'Warm charcoal borders prevent clinical coldness on dark', 'Border weight and color communicate depth over shadows', 'Code snippets are hero content, not supporting elements'],
    moodKeywords: ['electric', 'technical', 'energized', 'terminal'],
  },
  {
    id: 'warp',
    name: 'Warp',
    vibe: 'Terminal tool with warm contemplative design soul',
    category: 'dev-tools',
    colors: { primary: '#faf9f6', secondary: '#353534', background: '#0a0a0a', text: '#faf9f6', accent: '#868584' },
    typography: { font: 'Matter', weights: '400, 500', characteristics: 'Regular weight dominance creates calm texture; soft geometry signals humanity in developer tools; uppercase labels editorial-styled' },
    principles: ['Warm dark background prevents cold blue-tinted harshness', 'Nature photography interleaved with terminal screenshots', 'Semi-transparent borders create ghostly containment', 'Monochromatic warm grays eliminate color distraction'],
    moodKeywords: ['warm', 'contemplative', 'editorial', 'developer'],
  },
  {
    id: 'webflow',
    name: 'Webflow',
    vibe: 'Design without code through confident color and clarity',
    category: 'dev-tools',
    colors: { primary: '#146ef5', secondary: '#ffffff', background: '#ffffff', text: '#080808', accent: '#7a3dff' },
    typography: { font: 'WF Visual Sans Variable', weights: '400, 500, 600', characteristics: 'Variable font enables smooth weight transitions; confident default weight prevents timidity; measured negative tracking tightens display' },
    principles: ['Rich secondary palette adds visual variety without chaos', 'Translate hover animates buttons upward on interaction', 'Five-layer cascading shadow system creates sophisticated depth', 'Sharp small radius maintains professional conservatism'],
    moodKeywords: ['vibrant', 'confident', 'design-forward', 'functional'],
  },
  {
    id: 'wise',
    name: 'Wise',
    vibe: 'Bold fintech energy through extreme typographic weight',
    category: 'fintech',
    colors: { primary: '#9fe870', secondary: '#0e0f0c', background: '#ffffff', text: '#0e0f0c', accent: '#163300' },
    typography: { font: 'Wise Sans', weights: '900, 600, 400', characteristics: 'Weight 900 stamped headlines feel physical and pressed; tight line-height crushes text vertically; contextual alternates enhance every glyph' },
    principles: ['Extreme boldness announces fintech confidence loudly', 'Lime green on white feels alive and optimistic', 'Scale animations on hover and active create physicality', 'Ring shadows only; borders replace traditional elevation'],
    moodKeywords: ['bold', 'financial', 'energetic', 'confident'],
  },
  {
    id: 'xai',
    name: 'xAI',
    vibe: 'Brutalist darkness where infrastructure meets minimalism',
    category: 'ai',
    colors: { primary: '#ffffff', secondary: '#1f2228', background: '#1f2228', text: '#ffffff', accent: '#3b82f6' },
    typography: { font: 'GeistMono', weights: '300, 400', characteristics: 'Monospace at display scale commands rhythm; uppercase buttons with wide tracking signal technical authority; no typeface manipulation' },
    principles: ['Monospace as display font positions platform as infrastructure', 'Extreme whitespace generosity signals confident restraint', 'Sparse grid reflects information focus', 'Borders dim on hover reversing convention'],
    moodKeywords: ['brutalist', 'monochrome', 'technical', 'minimalist'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    vibe: 'Warm automation that feels human and approachable',
    category: 'productivity',
    colors: { primary: '#ff4f00', secondary: '#201515', background: '#fffefb', text: '#201515', accent: '#939084' },
    typography: { font: 'Degular Display / Inter', weights: '400, 500, 600, 900', characteristics: 'Degular compressed at tight line-height blocks headlines architecturally; three-font system shifts register from bold to functional to editorial elegance' },
    principles: ['Warm cream canvas feels organic like paper', 'Orange accent vivid but sparingly applied', 'Sand borders define structure over shadow elevation', 'Compressed headlines contrast generous section spacing'],
    moodKeywords: ['warm', 'approachable', 'architectural', 'human'],
  },
];

export const TOTAL_DESIGN_SYSTEMS = DESIGN_SYSTEMS.length;
